[package]
name = "fetch-node-remote"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0.113"
serde = { version = "1.0", features = ["derive"] }
colored = "2.1.0"
semver = "1.0.21"
chrono = "0.4"